dist:
  module: code.cloudfoundry.org/otel-collector-release/src/otel-collector
  name: otelcol-cf
  description: OpenTelemetry Collector for CloudFoundry
  otelcol_version: 0.134.0
  output_path: ../otel-collector
  version: 0.11.4
exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.135.0
  - gomod: go.opentelemetry.io/collector/exporter/otlpexporter v0.135.0
  - gomod: go.opentelemetry.io/collector/exporter/otlphttpexporter v0.135.0
  - gomod: go.opentelemetry.io/collector/exporter/nopexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/fileexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/splunkhecexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/datadogexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/kafkaexporter v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/syslogexporter v0.135.0
processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.135.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/transformprocessor v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/filterprocessor v0.135.0
receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/syslogreceiver v0.135.0
providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.41.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.41.0
extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.135.0